### ISSUE TITLE
Windows - Customize - Join specified domain OU

### ISSUE THREAD

**Issue by VickyWinner** [Terraform-VMWare-Modules/terraform-vsphere-vm#25]
Hello

I couldn't join to the domain under specific OU where I have access to.  Is there any option to specify OU name/path for the domain?

**Comment by jpatigny** [comment]
Hello,

As far as I know it's not possible to set the OU during the join domain.
You have multiple options : 
- Do the join domain after the costumozation via script/configuration manager and then you can specify the OU
- Use a terraform provider for Active directory and create your computer object upfront in the OU that you want
- Use redicmp command to put all domain joined computers to a specific OU instead of container computers >> https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc770619(v=ws.11)
