### ISSUE TITLE
Ignore Changes for template_uuid

### ISSUE THREAD

**Issue by chessser** [Terraform-VMWare-Modules/terraform-vsphere-vm#57]
I'm using v1.7 of terraform-provider-vsphere, and when updating the VCenter Template, the template_uuid changes, which means that when running a plan, it wants to re-create the VMs. This is inconvenient, as the state file needs to be updated to reflect the new template_uuid. Ideally the Terraform should not be re-creating the VM if the template changes.

Adding the following:
`lifecycle { ignore_changes = [ clone[0].template_uuid ] }`

After https://github.com/Terraform-VMWare-Modules/terraform-vsphere-vm/blob/455275a83fec49d5d19102f435857c5ec0bddc38/main.tf#L171
(inside the resource `"vsphere_virtual_machine" "Linux" {`)

Resolves the issue I am facing, but I appreciate this only resolves the issue locally. This works for me because I haven't configured https://github.com/Terraform-VMWare-Modules/terraform-vsphere-vm/blob/455275a83fec49d5d19102f435857c5ec0bddc38/variables.tf#L22 to be anything more than one. The way that I have configured means that is not optional either, and so it will affect all resources.

My Terraform knowledge is not good enough to configure it for every use case, but having this setting available would be very useful.

If anyone is able to suggest how this might be configured correctly?

Thanks,

**Comment by Arman-Keyoumarsi** [comment]
I believe that is by design. Usually the workflow would be; you create your template using Packer (or similar tool) and deploy it using Terraform., every time you want change your application you do that through updating your template.

I also agree with you as there are scenarios like Static infrastructure or even migration from one vCenter to another that might change your UUID and cause problem.

We should be able to fix this by introducing lifecycle to the module.

**Comment by Arman-Keyoumarsi** [comment]
Tried to implement it in the module but missed the fact that it needs literal values :).

Literal Values Only
The lifecycle settings all affect how Terraform constructs and traverses the dependency graph. As a result, only literal values can be used because the processing happens too early for arbitrary expression evaluation.

in the [documentation](https://www.terraform.io/docs/configuration/meta-arguments/lifecycle.html) there is a mention for "all" option for lists but I couldn't get it to work.

**Comment by kingnarmer** [comment]
@Arman-Keyoumarsi I'm encountering the exact same issue. The template UUID changes every few weeks, and I need a way to configure the module to ignore changes to the template UUID. Any advice would be greatly appreciated! Currently, the Terraform pipeline keeps recreating VMs that should remain unchanged. Thanks!

**Comment by kingnarmer** [comment]
@chessser  Were you able to find a workaround ?

**Comment by johnypony3** [comment]
@kingnarmer have you tried:

`lifecycle { ignore_changes = [ clone[0].template_uuid ] }`

**Comment by kingnarmer** [comment]
@johnypony3  How I pass this input to the module ?

**Comment by johnypony3** [comment]
@kingnarmer please search terraform docs for the `The lifecycle Meta-Argument`.

**Comment by damnsam** [comment]
I think the issue is that there is no way to make this an optional feature to pass into the module to allow for flexible usage.  Until terraform changes something to allow for this, I would suggest forking the module and adding that line for yourself or using a local copy instead of direct from GitHub.  This does pose the risk of missing any updates but, there hasn't been an update in a while :)

**Comment by johnypony3** [comment]
@damnsam Seems like its just the basic template changing and terraform wanting to recreate resources. :)

```
 The template UUID changes every few weeks, and I need a way to configure the module to ignore changes to the template UUID.
```
