### ISSUE TITLE
after cloning from template VM doesn't connect Network adapter (unchecked in properties)

### ISSUE THREAD

**Issue by atchaikovski** [Terraform-VMWare-Modules/terraform-vsphere-vm#70]
Could you please have a look. when customization is there any VM created from template won't get IP as adapters keep disconnected in freshly created VMs. when creating VM out of this template manually it gets IP/Network, properties show Network adapter option checked. VMware 6.7, vCenter 7.0. thank you!

**Comment by ncecere** [comment]
I was experiencing this issue as well, the problem was with my template.  I need to perform some extra step to enable customization via cloud-init.  just wondering what OS/platform are you trying to deploy?

**Comment by atchaikovski** [comment]
yes I was finally able to make a template somehow using kickstart so it
doesn't disconnect its LAN when powered-on.. but anyway looks strange,
still struggling with it (size is big when ovftool makes final steps). I've
used Centos7 as my base image.

пт, 22 янв. 2021 г. в 07:45, ncecere <notifications@github.com>:

**Comment by karma0** [comment]
Ran into this with Ubuntu 20.04 as my template on VSphere 7.  What was your workaround?

**Comment by atchaikovski** [comment]
> I was experiencing this issue as well, the problem was with my template. I need to perform some extra step to enable customization via cloud-init. just wondering what OS/platform are you trying to deploy?

I was doing some preparations of template already (CentOS 7), it's made for DHCPbut that's not an issue. when VM gets created with fixed IP it works fine. the reason of my question is how to force existing DDNS based on CentOS (or AD, I have one as well) to make records in DNS? seems I'm just doing something wrong with resource "dns_a_record" structure in terraform. my experience with terraform is just 2 months so far

**Comment by atchaikovski** [comment]
> Ran into this with Ubuntu 20.04 as my template on VSphere 7. What was your workaround?

unfortunately no workarounds as yet. learning syntax :)

**Comment by huntersneed** [comment]
Having the same issue. If anyone is able to resolve this, that would be greatly appreciated

**Comment by karma0** [comment]
This is working in my setup with an Ubuntu base image and then building an intermediate application base image after a lot of work testing/evaluating.  With that, this may not work for everyone since the path I took had a lot of back-tracking.

In the base image:

1. Follow the instructions here: https://kb.vmware.com/s/article/59557
2. Follow step 2 (step 1 seems to be resolved in the latest ubuntu and caused issues for me) here: https://kb.vmware.com/s/article/56409

If you're creating another template VM (I was using Vagrant to do just that) then do that now.  If you aren't, these next steps may need to go into your image along with the steps above.  These will disable `cloud-init` from controlling the network and fix the `netplan` configuration, essentially disabling all prior configuration and allow Terraform to take over the configuration of the network while generating the VMs.

1. `echo "network: { config: disabled }" | sudo tee /etc/cloud/cloud.cfg.d/99_netplan_enable.cfg`
2. `find /etc/netplan -iname '*.yaml' | grep -v '\/99-netcfg-vmware.yaml$' | while read a; do sudo mv -v "${a}"{,.dist}; done`
3. `sudo netplan generate`

Good luck!
