### ISSUE TITLE
For Windows VMs. Please allow Different Names for VM Logical Name and Windows Host (Netbios) Name

### ISSUE THREAD

**Issue by RudolfAchter** [Terraform-VMWare-Modules/terraform-vsphere-vm#95]
I want do deploy a single Windows vm. 
i Want it have FQDN myhost.mydomain.com and join it my ActiveDirectory Domain mydomain.com

So i set

```
staticvmname            = "myhost.mydomain.com"
windomain                 = "mydomain.com"
```

i get this error

```
Error: error sending customization spec: A specified parameter was not correct: spec.identity.userData.computerName
```

ok maybe it has to do with NETBIOS Names only allowing 15 chars (and no Dots i think)

So i set
```
staticvmname            = "myhost"
windomain                 = "mydomain.com"
```
this works

But i want my VM-Name to reflect the full FQDN ` myhost.mydomain.com`. This seems not possible for me now
can you help me here?

**Comment by damnsam** [comment]
This intrigued me and I have a temp working version where the VM name is the FQDN but only if a variable is set to "true".  It works with both staticvmname and dynamic vmnames, appending the domain variable (must be set for windows system).  I didn't use windomain because it can be different than the windows AD domain being joined.  Arman, is this something that you want me to add as a pull request? Is there any scenario where we dont want this or change how it works?

**Comment by Arman-Keyoumarsi** [comment]
> This intrigued me and I have a temp working version where the VM name is the FQDN but only if a variable is set to "true". It works with both staticvmname and dynamic vmnames, appending the domain variable (must be set for windows system). I didn't use windomain because it can be different than the windows AD domain being joined. Arman, is this something that you want me to add as a pull request? Is there any scenario where we dont want this or change how it works?

@damnsam I checked your fork for the FQDN, it looks good and wont break any compatibility. do a PR and I will merge it. Thanks!!
