### ISSUE TITLE
Add support for IPv6 address

### ISSUE THREAD

**Issue by Clement87** [Terraform-VMWare-Modules/terraform-vsphere-vm#96]
Hi,
I would like to use this module with IPv6 support.  
I believe it needs a major rewrite of the *network* part.  
What do you think? What would be the best implementation?  
I'm ready to help.
Best, Clement

**Comment by Arman-Keyoumarsi** [comment]
Hi Clement, 

I am open to it as long as it doesn't add extra complexity and break backward compatibility. 

```hcl
#One way I can think of solving it, but not sure since haven't tried it actually :)
dynamic "network_interface" {
        for_each = keys(var.network)
        content {
          ipv4_address = var.network[keys(var.network)[network_interface.key]][count.index]
          ipv4_netmask = "%{if length(var.ipv4submask) == 1}${var.ipv4submask[0]}%{else}${var.ipv4submask[network_interface.key]}%{endif}"
          # we can add same values with default to null variables here then we can just use a switch to toggle between ipv4 and v6
        }
      }
      dns_server_list = var.dns_server_list
      dns_suffix_list = var.dns_suffix_list
      ipv4_gateway    = var.vmgateway
      ipv6_gateway    = default to Null  and use switch to null the other one
    }
```

To contribute, please follow [contribution guidelines](https://github.com/Terraform-VMWare-Modules/terraform-vsphere-vm/blob/master/CONTRIBUTING.md)

**Comment by Clement87** [comment]
Thanks for the suggestion, does that mean we can only have an IPv4 **or** an IPv6 ? Any idea on how to have both ?

**Comment by einhirn** [comment]
I'll look into it, because I want to provision VMs with IPv4 and IPv6.

One option I'd propose would use a new variable "network_v6" which needs to be defined with the same keys and length of list as "network", containing ipv6 adresses. 
The other approach would generalize multiple adresses per network interface, autodetecting IPv4/v6 and try to sort this without breaking backwards compatibility in the above code snippet.
